- id: openapi-lint
  name: Cimpress OpenAPI Linter
  description: This hook lints OpenAPI spec according to the rfc specifications of RFC-2
  entry: spectral lint --ruleset /app/.spectral.yml
  language: docker
  files: \.(json|yaml|yml)$
- id: openapi-lint-node
  name: Cimpress OpenAPI Linter using Node Runtime
  description: This hook lints OpenAPI spec according to the rfc specifications of RFC-2
  language: node
  files: \.(json|yaml|yml)$
  entry: spectral
